version: '3'
services:
  precise:
    build:
      context: ./builder
      args:
        ubuntu_version: precise
        php_version: 5.3.10
        php_packages: php5 php5-cli php5-dev php-pear
        php_ext_conf_dir: /etc/php5/conf.d
        oci8_version: 2.0.12
    volumes:
      - ./build/precise:/host

  trusty:
    build:
      context: ./builder
      args:
        ubuntu_version: trusty
        php_version: 5.5.9
        php_packages: php5 php5-cli php5-dev
        php_ext_conf_dir: /etc/php5/mods-available
        oci8_version: 2.0.12
    volumes:
      - ./build/trusty:/host

  xenial:
    build:
      context: ./builder
      args:
        ubuntu_version: xenial
        php_version: 7.0.30
        php_packages: php7.0 php7.0-cli php7.0-dev
        php_ext_conf_dir: /etc/php/7.0/mods-available
        oci8_version: 2.1.8
    volumes:
      - ./build/xenial:/host

  bionic:
    build:
      context: ./builder
      args:
        ubuntu_version: bionic
        php_version: 7.2.5
        php_packages: php7.2 php7.2-cli php7.2-dev
        php_ext_conf_dir: /etc/php/7.2/mods-available
        oci8_version: 2.1.8
    volumes:
      - ./build/bionic:/host

  focal:
    build:
      context: ./builder
      args:
        ubuntu_version: focal
        php_version: 7.3.18
        php_packages: php7.3-common php7.3 php7.3-cli php7.3-dev php7.3-xml
        php_ext_conf_dir: /etc/php/7.3/mods-available
        oci8_version: 2.2.0
    volumes:
      - ./build/focal:/host
